name: medq
description: MedQ - Adaptive Medical Study Companion
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.1
  firebase_auth: ^5.4.1
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.4.0
  cloud_functions: ^5.2.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  go_router: ^14.8.1
  pdfrx: ^1.0.92
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.4
  connectivity_plus: ^6.1.1
  intl: ^0.19.0
  percent_indicator: ^4.2.3
  flutter_slidable: ^3.1.1
  table_calendar: ^3.1.3
  file_picker: ^8.1.6
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  build_runner: ^2.4.13
  riverpod_generator: ^2.6.2
  mockito: ^5.4.4
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
